# Generated by Django 5.2.7 on 2025-11-20 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('skills', models.JSONField()),
                ('interests', models.JSONField()),
                ('year', models.IntegerField()),
                ('branch', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('gmail', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
            ],
        ),
    ]
